<?php

namespace App\Models;


use App\Filters\SearchFilter;
use App\Queries\SearchBuilder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Search extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'slug', 'image', 'category_id', 'color', 'size'];
    //protected $guarded = ['id', 'created_at', 'updated_at'];
public function newEloquentBuilder($query)
{
    return new SearchBuilder($query); // TODO: Change the autogenerated stub
}

public function newQueryFilter()
{
    return new SearchFilter(); // TODO: Change the autogenerated stub
}

}
